name: Deploy Arise to html branch
permissions:
  contents: write
on:
  push:
    branches: ["blog-prod","staging"]
    paths: ['arise-source/**']
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Arise
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Set deployment variables
        run: |
          if [[ $GITHUB_REF == 'refs/heads/blog-prod' ]]; then
            echo "OUTPUT_BRANCH=html" >> "$GITHUB_ENV"
            echo "SITE_URL=cyberia.robeson.me" >> "$GITHUB_ENV"
            echo "Workflow running from blog-prod branch. Will deploy to production."
          else
            echo "OUTPUT_BRANCH=html-staging" >> "$GITHUB_ENV"
            echo "SITE_URL=html-staging.d33b4ugcqkd7c3.amplifyapp.com" >> "$GITHUB_ENV"
            echo "Workflow running from staging branch. Will deploy to staging."
          fi

      - name: Build Arise
        id: build
        run: |
          if ! bash arise build; then
            echo "::error::Build failed"
            exit 1
          fi

      - name: Replace URLs
        run: |
          # Source the config file
          source tools/urls.conf
          
          # Create array of all URLs from config
          OLD_URLS=("$PROD_URL" "$STAGING_URL" "$DEV_URL")
          
          # Replace all URLs except the target one
          for url in "${OLD_URLS[@]}"; do
            if [ "$url" != "${{ env.SITE_URL }}" ]; then
              find arise-out -type f -exec sed -i "s|$url|${{ env.SITE_URL }}|g" {} +
            fi
          done

      - name: Push to live branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: ${{ env.OUTPUT_BRANCH }}
          FOLDER: arise-out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Commit: ({sha}) {msg}"