# .github/workflows/arise-deploy.yml
name: Deploy Arise to html branch
permissions:
  contents: write
on:
  # Runs on pushes targeting the default branch
  ##Only runs when the push contains changes to the site source itself. No need to rebuild the site if it's just program files that have changed.
  push:
    branches: ["blog-prod","staging"]
    paths: ['arise-source/**']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Arise
    steps:
      - name: Check if we should deploy to prod or staging
        run: |
          echo "SMART DEPLOY"
          echo "============"
          echo "We only want to deploy to prod if the branch that triggered this workflow is 'blog-prod'. Otherwise, we want the site to be deployed to staging..."
          echo ""
          if [[ $GITHUB_REF == 'refs/heads/blog-prod' ]]; then
              # Feel free to change the value of OUTPUT_BRANCH. This is where Arise artefacts will be deployed for production.
              echo "OUTPUT_BRANCH=html" >> "$GITHUB_ENV"
              echo "Workflow running from main branch. Pushing results to production deployment branch (html)."
          else
              # Feel free to change the value of OUTPUT_BRANCH. This is where Arise artefacts will be deployed for staging.
              echo "OUTPUT_BRANCH=html-staging" >> "$GITHUB_ENV"
              echo "Workflow running from a development branch. Pushing results to staging deployment branch (html-staging)."
          fi

      - name: git-checkout
        uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      # - name: Version CSS
      #   run: sed -i -E "s/main\.css\?[0-9A-Za-z]*/main.css\?$(tr -dc A-Za-z0-9 </dev/urandom | head -c 8)/gm" arise-source/config/header.html 

      - name: Build Arise
        id: build
        run: |
          if ! bash arise build; then
            echo "::error::Build failed"
            exit 1
          fi
    
      - name: Push to live branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: ${{ env.OUTPUT_BRANCH }} # If you want to change this, change it in the step above. This allows us to intelligently deploy to production from main or staging if we're on a dev branch.
          FOLDER: arise-out # The Arise build output location. Don't change this.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Handled automatically -- Don't change this unless you're pushing to a different repo
          MESSAGE: "Commit: ({sha}) {msg}" # Copies commit msg from main to the deploy version branch

      # - name: Cloudflare Purge Cache
      #   uses: jakejarvis/cloudflare-purge-action@v0.3.0
      #   env:
      #     CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
      #     CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}