name: ShellCheck
permissions:
  contents: read
on:
  push:
    paths: ['tools/**']
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Shellcheck Tools
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: ./tools
          ignore_paths: ./tools/.hooks